### ISSUE TITLE
[SUGGESTION] Add a PROPER wiki with explanations of what each API does

### ISSUE THREAD

**Issue by MrPigeontheCoder** [try-supernova/supernova#45]
that's it

**Comment by MrPigeontheCoder** [comment]
> Let's welcome this new user to our community!

what?

**Comment by its-pablo** [comment]
Hello @MrPigeontheCoder ! There is a documentation reference at system41/open99-docs.
I agree there should be some sort of developer api documentation reference as well.
I have many ideas on implementing a second api as well, so perhaps they should be separated into different repos (once I make and write the docs for the second api)
A lot of work is going to be done with open99 in 2023, and currently the entirety of the project is actually put on hold until I get a better development environment.

Additionally, open99 is unfinished, buggy, and unstable. This is mainly because of what I said before, however I hope for the project to be finished in around a year (im gonna power through in 2023)

**Comment by MrPigeontheCoder** [comment]
ok thanks

**Comment by its-pablo** [comment]
this hasn't been done yet but I'm going to close the issue because the docs are a work in progress and they grow while the project grows
